// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ColorCode struct {
	UserID     string
	ColorCode1 string
	ColorCode2 string
}

type EisaFile struct {
	UserID    string
	FilePath  string
	CreatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type User struct {
	UserID         string
	Mail           string
	Name           string
	HashedPassword string
}
