// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/K-Kizuku/eisa-auth/db"
	"github.com/K-Kizuku/eisa-auth/internal/app/handler"
	"github.com/K-Kizuku/eisa-auth/internal/app/repository"
	"github.com/K-Kizuku/eisa-auth/internal/app/service"
)

// Injectors from wire.go:

func InitHandler() *handler.Root {
	queries := db.New()
	iUserRepository := repository.NewUserRepository(queries)
	iUserService := service.NewUserService(iUserRepository)
	iUserHandler := handler.NewUserHandler(iUserService)
	root := handler.New(iUserHandler)
	return root
}
