name: Migration

on:
  push:
    branches:
      - main
    paths:
      - "db/migrations/*"

env:
  PROXY_IMAGE: gcr.io/cloudsql-docker/gce-proxy
  CLOUDSQL_INSTANCE_CONNECTION_NAME: "${{ secrets.PROJECT_ID }}:${{ secrets.REGION }}:${{ secrets.CLOUDSQL_INSTANCE }}"
  POSTGRES_DSN: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@127.0.0.1:5432/${{ secrets.POSTGRES_DATABASE }}?sslmode=disable

jobs:
  migrate-db:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: db

    steps:
      - uses: actions/checkout@v4

      - name: Start Cloud SQL Proxy
        run: |
          echo '${{ secrets.CLOUDSQL_SA_KEY }}' > sa_key
          docker pull $PROXY_IMAGE
          docker run -d \
            -v $PWD/sa_key:/config \
            -p 127.0.0.1:5432:5432 \
            $PROXY_IMAGE /cloud_sql_proxy \
            -instances=$CLOUDSQL_INSTANCE_CONNECTION_NAME=tcp:0.0.0.0:5432 \
            -credential_file=/config

      - name: Install migrate
        run: |
          curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | sudo apt-key add -
          echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/migrate.list
          sudo apt-get update
          sudo apt-get install -y migrate

      - name: Migrate DB (up)
        run: migrate -path "./migrations/" -database "$POSTGRES_DSN" up
